threadmill/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/seed'
  get 'home/work_hard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

threadmill/app/models/user.rb
# frozen_string_literal: true

class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :first_name, type: String
  field :last_name, type: String
  field :category, type: String
  field :last_message, type: String
end

threadmill/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

threadmill/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def seed
    1000.times do |i|
      User.create(first_name: "First #{i}", last_name: "Last #{i}", category: category(i))
    end
    redirect_to root_path
  end

  def work_hard
    1000.times do |i|
      HardJob.perform_async(category(i), "message at #{Time.now}")
    end
    redirect_to root_path
  end

  private

  def category(i)
    %w[admin user guest][i % 3]
  end
end

threadmill/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render plain: 'Error'
    end
  end
end

threadmill/app/helpers/application_helper.rb
module ApplicationHelper
end

threadmill/app/helpers/home_helper.rb
module HomeHelper
end

threadmill/app/helpers/users_helper.rb
module UsersHelper
end

threadmill/app/views/home/index.html.erb
<h1>Home#index</h1>
<p><%= link_to 'Seed database', home_seed_path %></p>
<p><%= link_to 'Work hard', home_work_hard_path %></p>

threadmill/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Threadmill</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>